# Generated by Django 5.1.5 on 2025-02-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configpanel', '0002_prompt_alter_adjectivetocountry_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
