# Generated by Django 5.1.5 on 2025-02-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configpanel', '0003_rename_date_created_newsarticle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.URLField(help_text='Введите ссылку на оригинальную статью', unique=True, verbose_name='Ссылка на статью'),
        ),
    ]
