# Generated by Django 5.1.5 on 2025-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configpanel", "0004_alter_newsarticle_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Доступен ли источник для парсинга",
                verbose_name="Активен",
            ),
        ),
    ]
